name: edumarkaz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Splash Screen
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Afacad
      fonts:
        - asset: assets/fonts/afacad_regular.ttf
        - asset: assets/fonts/afacad_medium.ttf
          weight: 500
        - asset: assets/fonts/afacad_bold.ttf
          weight: 700

    - family: Apercu
      fonts:
        - asset: assets/fonts/apercu_regular.ttf
        - asset: assets/fonts/apercu_medium.ttf
          weight: 500
        - asset: assets/fonts/apercu_bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"  # Background color
  image: assets/images/logo_circle.png  # Your splash screen logo
  android_12:
    image: assets/images/logo_circle.png
    color: "#ffffff"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_circle"  # Your app icon path
  adaptive_icon_background: "#ffffff"  # Adaptive background color
  adaptive_icon_foreground: "assets/images/logo_circle.png"